// <auto-generated />
namespace GladiatorTycoon.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_bodyparts_to_race : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_bodyparts_to_race));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060429158_added_bodyparts_to_race"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
