// <auto-generated />
namespace GladiatorTycoon.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class renamed_speed_to_skill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamed_speed_to_skill));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050600151_renamed_speed_to_skill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
