// <auto-generated />
namespace GladiatorTycoon.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_testing_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_testing_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201906131332381_add_testing_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
