// <auto-generated />
namespace GladiatorTycoon.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changed_bodyparts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_bodyparts));
        
        string IMigrationMetadata.Id
        {
            get { return "201905061222409_changed_bodyparts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
