// <auto-generated />
namespace DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedspeedandbravery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedspeedandbravery));
        
        string IMigrationMetadata.Id
        {
            get { return "202105271621518_added-speed-and-bravery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
